/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.ProjectBL;
import com.uia.is12.business.UserBL;
import com.uia.is12.business.TaskBL;
import com.uia.is12.data.ProjectDAO;
import com.uia.is12.data.UserDAO;
import com.uia.is12.data.TaskDAO;
import com.uia.is12.domain.Projects;
import com.uia.is12.domain.Tarea;
import com.uia.is12.domain.User;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Pierre
 */
public class IssuesTrackerTarea extends javax.swing.JFrame {

    /**
     * Creates new form IssuesTrackerTarea
     */
    public String username;
    UserDAO dao = new UserDAO();
    public IssuesTrackerTarea() {
        initComponents();
        ProjectBL bl = new ProjectBL();
        Projects pr = new Projects();
        ProjectDAO dao = new ProjectDAO();
        
        
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbMostrarProyectos.setModel(modelo);
        tbMostrarProyectos.setSelectionBackground(Color.cyan);
        tbMostrarProyectos.setToolTipText("Proyectos Registrados");
        try {
            ResultSet rs = dao.MostrarProyectos(pr);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btTarea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDecripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMostrarProyectos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox();
        jComboBoxPrivacidad = new javax.swing.JComboBox();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Añadir Tarea: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Nombre de la Tarea:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 261, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 746, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 622, 10));

        btTarea.setText("Asignar Tarea");
        btTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 314, -1, -1));

        txtDecripcion.setColumns(20);
        txtDecripcion.setRows(5);
        jScrollPane1.setViewportView(txtDecripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 261, 63));

        tbMostrarProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbMostrarProyectos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 420, 250));

        jLabel5.setText("Privacidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel6.setText("Prioridad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));
        getContentPane().add(jComboBoxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, -1));

        jComboBoxPrivacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Publico", "Privado" }));
        getContentPane().add(jComboBoxPrivacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, -1));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, -1));

        jLabel7.setText("Asignar a Proyecto: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ir");

        jMenuItem2.setText("Mantenimiento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTareaActionPerformed
        Tarea task = new Tarea();
        TaskBL bl = new TaskBL();
        task.setId(Integer.parseInt(txtId.getText()));
        task.setNombre(txtNombreTarea.getText());
        task.setDescripcion(txtDecripcion.getText());
        int prioridad=this.jComboBoxPrioridad.getSelectedIndex();
        if (prioridad==0) {
            String prioridadA = "Alta";
            task.setPrioridad(prioridadA);
        }else{
            if (prioridad==1) {
                String prioridadA = "Media";
                task.setPrioridad(prioridadA);
            }else{
                if (prioridad==2) {
                    String prioridadA = "Baja";
                    task.setPrioridad(prioridadA);
                }
            }
            int privacidad = this.jComboBoxPrivacidad.getSelectedIndex();
            if (privacidad==0) {
            String privacidadA = "Publico";
            task.setPrivacidad(privacidadA);
        }else{
            if (privacidad==1) {
                String privacidadA = "Privado";
               task.setPrivacidad(privacidadA);
            }
        }
            if (tbMostrarProyectos.getSelectedRow() != -1) {
            username = tbMostrarProyectos.getModel().getValueAt(tbMostrarProyectos.getSelectedRow(), 0).toString();
            JOptionPane.showMessageDialog(null, username);
            task.setAsignar(username);
        }
            
        try {
            bl.agregarTarea(task);
            JOptionPane.showMessageDialog(null, "Tarea agregada\nNombre de la Tarea:"+task.getNombre()+"\nAsignado a:"+task.getAsignar());
            txtId.setText("");
            txtDecripcion.setText("");
            txtNombreTarea.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(IssuesTrackerCreateIssue.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btTareaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerLog is = new IssuesTrackerLog();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        IssuesTrackerPrincipal is = new IssuesTrackerPrincipal();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'||c>'9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuesTrackerTarea().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTarea;
    private javax.swing.JComboBox jComboBoxPrioridad;
    private javax.swing.JComboBox jComboBoxPrivacidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbMostrarProyectos;
    private javax.swing.JTextArea txtDecripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreTarea;
    // End of variables declaration//GEN-END:variables
}
