/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.IssuesBL;
import com.uia.is12.business.ProjectBL;
import com.uia.is12.business.UserBL;
import com.uia.is12.data.UserDAO;
import com.uia.is12.domain.Issues;
import com.uia.is12.domain.Projects;
import com.uia.is12.domain.User;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Pierre
 */
public class IssuesTrackerProyecto extends javax.swing.JFrame {

    /**
     * Creates new form IssuesTrackerProyecto
     */
   public String username;
    UserDAO dao = new UserDAO();
    public IssuesTrackerProyecto() {
        initComponents();
        UserBL bl=new UserBL();
        User usuario=new User();
        UserDAO dao = new UserDAO();
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbUserName.setModel(modelo);
        tbUserName.setSelectionBackground(Color.RED);
        tbUserName.setToolTipText("Usuarios Registrados");
        try {
            ResultSet rs=dao.MostrarUserName(usuario);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbUsLog = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcioin = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        brAgregarPro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUserName = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox();
        jComboBoxPrivacidad = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Asignar un proyecto: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Asignar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setText("Nombre del Proyecto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel5.setText("Descripción: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 177, -1, -1));
        getContentPane().add(lbUsLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));
        getContentPane().add(txtNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 200, -1));

        txtDescripcioin.setColumns(20);
        txtDescripcioin.setRows(5);
        jScrollPane1.setViewportView(txtDescripcioin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 145, 200, 150));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 739, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 719, 10));

        brAgregarPro.setText("Agregar");
        brAgregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brAgregarProActionPerformed(evt);
            }
        });
        getContentPane().add(brAgregarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 424, -1, -1));

        tbUserName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbUserName);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 216, 136));

        jLabel3.setText("Prioridad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        jLabel7.setText("Privacidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jComboBoxPrioridad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Media", "Baja" }));
        getContentPane().add(jComboBoxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 200, -1));

        jComboBoxPrivacidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Publico", "Privado" }));
        getContentPane().add(jComboBoxPrivacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 200, -1));

        jLabel8.setText("ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, -1));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ir");

        jMenuItem3.setText("Mantenimiento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brAgregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brAgregarProActionPerformed
        Projects pr = new Projects();
        ProjectBL bl = new ProjectBL();
        pr.setId(Integer.parseInt(txtId.getText()));
        pr.setNombre(txtNombreProyecto.getText());
        pr.setDescripcion(txtDescripcioin.getText());
        int prioridad=this.jComboBoxPrioridad.getSelectedIndex();
        if (prioridad==0) {
            String prioridadA = "Alta";
            pr.setPrioridad(prioridadA);
        }else{
            if (prioridad==1) {
                String prioridadA = "Media";
                pr.setPrioridad(prioridadA);
            }else{
                if (prioridad==2) {
                    String prioridadA = "Baja";
                    pr.setPrioridad(prioridadA);
                }
            }
            int privacidad = this.jComboBoxPrivacidad.getSelectedIndex();
            if (privacidad==0) {
            String privacidadA = "Publico";
            pr.setPrivacidad(privacidadA);
        }else{
            if (privacidad==1) {
                String privacidadA = "Privado";
               pr.setPrivacidad(privacidadA);
            }
        }
            if (tbUserName.getSelectedRow() != -1) {
            username = tbUserName.getModel().getValueAt(tbUserName.getSelectedRow(), 0).toString();
            JOptionPane.showMessageDialog(null, username);
            pr.setAsignar(username);
            txtId.setText("");
            txtDescripcioin.setText("");
            txtNombreProyecto.setText("");
        }
            
        try {
            bl.agregarProyecto(pr);
            JOptionPane.showMessageDialog(null, "Proyecto agregado\nNombre del Proyecto:"+pr.getNombre()+"\nAsignado a:"+pr.getAsignar());
        } catch (SQLException ex) {
            Logger.getLogger(IssuesTrackerCreateIssue.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_brAgregarProActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IssuesTrackerLog is = new IssuesTrackerLog();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        IssuesTrackerPrincipal is = new IssuesTrackerPrincipal();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        char c = evt.getKeyChar();
        if (c<'0'||c>'9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuesTrackerProyecto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brAgregarPro;
    private javax.swing.JComboBox jComboBoxPrioridad;
    private javax.swing.JComboBox jComboBoxPrivacidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel lbUsLog;
    private javax.swing.JTable tbUserName;
    private javax.swing.JTextArea txtDescripcioin;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
