/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uia.is12.view;

import com.uia.is12.business.IssuesBL;
import com.uia.is12.business.ProjectBL;
import com.uia.is12.business.UserBL;
import com.uia.is12.business.TaskBL;
import com.uia.is12.data.IssuesDAO;
import com.uia.is12.data.ProjectDAO;
import com.uia.is12.data.UserDAO;
import com.uia.is12.data.TaskDAO;
import com.uia.is12.domain.Issues;
import com.uia.is12.domain.Projects;
import com.uia.is12.domain.Tarea;
import com.uia.is12.domain.User;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Pierre
 */
public class IssuesTrackerPrincipal extends javax.swing.JFrame {
    UserBL bl = new UserBL();
    /**
     * Creates new form IssuesTrackerPrincipal
     */
    public IssuesTrackerPrincipal() {
        initComponents();
       
        User usuario = new User();
        usuario.setNombreDeUsuario(lbUsuarioLogeado.getText());
        tbMostrarDatos.setSelectionBackground(Color.BLUE);
        
    }
    
    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMostrarDatos = new javax.swing.JTable();
        lbUsuarioLogeado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btMostrarDatos = new javax.swing.JButton();
        btMostrarIssues = new javax.swing.JButton();
        btMostrarProyectos = new javax.swing.JButton();
        btMostrarTareas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btEliminarUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMostrarDatos);

        jButton1.setText("Agregar Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Issue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar proyecto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar Tarea");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Agregar Proyecto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar Tarea");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Agregar Issue");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btMostrarDatos.setText("Mostrar Usuarios");
        btMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarDatosActionPerformed(evt);
            }
        });

        btMostrarIssues.setText("Mostrar Issues");
        btMostrarIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarIssuesActionPerformed(evt);
            }
        });

        btMostrarProyectos.setText("Mostrar Proyectos");
        btMostrarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarProyectosActionPerformed(evt);
            }
        });

        btMostrarTareas.setText("Mostrar Tareas");
        btMostrarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTareasActionPerformed(evt);
            }
        });

        btEliminarUsuario.setText("Eliminar Usuario");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cerrar sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1034, 1034, 1034)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addGap(166, 166, 166)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbUsuarioLogeado)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btMostrarDatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMostrarProyectos)
                                .addGap(22, 22, 22)
                                .addComponent(btMostrarTareas)
                                .addGap(18, 18, 18)
                                .addComponent(btMostrarIssues))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(btEliminarUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 712, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuarioLogeado)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(btEliminarUsuario))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMostrarIssues)
                    .addComponent(btMostrarProyectos)
                    .addComponent(btMostrarTareas)
                    .addComponent(btMostrarDatos))
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerRegister rg = new IssuesTrackerRegister();
        this.dispose();
        rg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerProyecto pr = new IssuesTrackerProyecto();
        this.dispose();
        pr.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerTarea tr = new IssuesTrackerTarea();
        this.dispose();
        tr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerCreateIssue is = new IssuesTrackerCreateIssue();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerEliminarProyecto el = new IssuesTrackerEliminarProyecto();
        this.dispose();
        el.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerEliminarTarea el = new IssuesTrackerEliminarTarea();
        this.dispose();
        el.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerEliminarIssue el = new IssuesTrackerEliminarIssue();
        this.dispose();
        el.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        IssuesTrackerLog is = new IssuesTrackerLog();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarDatosActionPerformed
        // TODO add your handling code here:
         UserBL bl=new UserBL();
        User usuario=new User();
        UserDAO dao = new UserDAO();
        
        
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbMostrarDatos.setModel(modelo);
        try {
            ResultSet rs=dao.MostrarUsuarios(usuario);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
            
    }//GEN-LAST:event_btMostrarDatosActionPerformed

    private void btMostrarIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarIssuesActionPerformed
        // TODO add your handling code here:
        IssuesBL bl=new IssuesBL();
        Issues isu = new Issues();
        IssuesDAO dao = new IssuesDAO();
        
        
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbMostrarDatos.setModel(modelo);
        try {
            ResultSet rs=dao.MostrarIssues(isu);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_btMostrarIssuesActionPerformed

    private void btMostrarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarProyectosActionPerformed
        ProjectBL bl = new ProjectBL();
        Projects pr = new Projects();
        ProjectDAO dao = new ProjectDAO();
        
        
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbMostrarDatos.setModel(modelo);
        try {
            ResultSet rs = dao.MostrarProyectosEnTable(pr);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_btMostrarProyectosActionPerformed

    private void btMostrarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTareasActionPerformed
        TaskBL bl = new TaskBL();
        Tarea task = new Tarea();
        TaskDAO dao = new TaskDAO();
        
        
        DefaultTableModel modelo=new DefaultTableModel();
        this.tbMostrarDatos.setModel(modelo);
        try {
            ResultSet rs = dao.MostrarTareas(task);
            
            ResultSetMetaData rsm=rs.getMetaData();
            int colum=rsm.getColumnCount();
            
            for(int i=1;i<=colum;i++){
                modelo.addColumn(rsm.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object [] fila=new Object[colum];
                
                for(int i=0;i<colum;i++){
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
                }
                
                
            }catch (SQLException ex) {
                 Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_btMostrarTareasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuesTrackerPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuesTrackerPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminarUsuario;
    private javax.swing.JButton btMostrarDatos;
    private javax.swing.JButton btMostrarIssues;
    private javax.swing.JButton btMostrarProyectos;
    private javax.swing.JButton btMostrarTareas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JLabel lbUsuarioLogeado;
    private javax.swing.JTable tbMostrarDatos;
    // End of variables declaration//GEN-END:variables
}
